import * as THREE from 'three';
import { CAMPUS } from './config.js';

const DEG = Math.PI / 180;
const METERS_LAT = 110574;
const METERS_LNG = 111320 * Math.cos(CAMPUS.spawn.lat * DEG);
const localToLngLat = (x, z) => ({ lng: CAMPUS.spawn.lng + x / METERS_LNG, lat: CAMPUS.spawn.lat - z / METERS_LAT });
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));

function disposeObject(root) {
  if (!root) return;
  const materials = new Set();
  root.traverse?.(obj => {
    obj.userData?.disposeTexture?.dispose?.();
    obj.geometry?.dispose?.();
    if (Array.isArray(obj.material)) obj.material.forEach(m => materials.add(m));
    else if (obj.material) materials.add(obj.material);
  });
  for (const material of materials) material?.dispose?.();
  root.removeFromParent?.();
}

function disposeGroupChildren(group) {
  if (!group) return;
  for (const child of [...group.children]) disposeObject(child);
  group.clear();
}

export function prepareStructureReloadV0181(world) {
  // Rectorado is generated by the legacy structure stage. Once v0.17 replaces the
  // generic building layer it is reparented to the scene; therefore a new scan must
  // explicitly dispose the previous copy or every scan leaks another Rectorado.
  if (world?.rectoradoDetail) {
    disposeObject(world.rectoradoDetail);
    world.rectoradoDetail = null;
  }
  disposeGroupChildren(world?.buildingGroup);
}

function pointSegmentDistanceSq(ax, az, bx, bz, px, pz) {
  const vx = bx - ax, vz = bz - az, wx = px - ax, wz = pz - az;
  const vv = vx * vx + vz * vz;
  const t = vv > 1e-8 ? clamp((wx * vx + wz * vz) / vv, 0, 1) : 0;
  const dx = px - (ax + vx * t), dz = pz - (az + vz * t);
  return dx * dx + dz * dz;
}

function candidateTreeColliders(world, a, b, pad = 1) {
  const grid = world.activeTreeColliderGrid;
  const cell = world.treeColliderCellM || 18;
  if (!grid?.size) return [];
  const minX = Math.floor((Math.min(a.x, b.x) - pad) / cell), maxX = Math.floor((Math.max(a.x, b.x) + pad) / cell);
  const minZ = Math.floor((Math.min(a.z, b.z) - pad) / cell), maxZ = Math.floor((Math.max(a.z, b.z) + pad) / cell);
  const out = [];
  for (let x = minX; x <= maxX; x++) for (let z = minZ; z <= maxZ; z++) {
    const bucket = grid.get(`${x}:${z}`);
    if (bucket) out.push(...bucket);
  }
  return out;
}

function enrichTreeColliders(world, x, z) {
  if (!world.forestDatabase || !world.activeTreeColliders?.length) return;
  const active = new Map(world.activeTreeColliders.map(c => [c.id, c]));
  for (const [, tree] of world.forestDatabase.detailedTreesAround(x, z, 90)) {
    const collider = active.get(tree.id);
    if (!collider) continue;
    const baseY = world.forestDatabase.surfaceY(tree);
    collider.baseY = baseY;
    collider.topY = baseY + tree.height;
    collider.height = tree.height;
  }
}

function snapUnderstoryToTerrain(world) {
  const terrain = world.__terrainOnlyElevation || world.getSurfaceElevation || world.getElevation?.bind(world);
  if (!terrain) return;
  const matrix = new THREE.Matrix4();
  const pos = new THREE.Vector3(), scale = new THREE.Vector3();
  const quat = new THREE.Quaternion();
  const meshes = [
    [world.veg?.shrub, 0], [world.veg?.herb, 0], [world.veg?.vine, 0], [world.veg?.epiphyte, .8]
  ];
  for (const [mesh, offsetY] of meshes) {
    if (!mesh?.count) continue;
    for (let i = 0; i < mesh.count; i++) {
      mesh.getMatrixAt(i, matrix);
      matrix.decompose(pos, quat, scale);
      const ll = localToLngLat(pos.x, pos.z);
      const y = terrain(ll.lng, ll.lat) - world.originElev;
      if (!Number.isFinite(y)) continue;
      pos.y = y + offsetY;
      matrix.compose(pos, quat, scale);
      mesh.setMatrixAt(i, matrix);
    }
    mesh.instanceMatrix.needsUpdate = true;
  }
}

function installForestGuards(world) {
  if (world.__forestStabilityV0181 || !world.refreshVegetation) return;
  world.__forestStabilityV0181 = true;
  const baseRefresh = world.refreshVegetation.bind(world);
  world.refreshVegetation = function(x, z, now) {
    const previousRefresh = this.forestLastRefresh;
    const result = baseRefresh(x, z, now);
    if (this.forestLastRefresh !== previousRefresh) {
      enrichTreeColliders(this, x, z);
      snapUnderstoryToTerrain(this);
    }
    return result;
  };

  world.pathBlockedTree = function(a, b, radius = .38) {
    if (!this.treesEnabled) return false;
    const ll = localToLngLat(a.x, a.z);
    const surface = this.getWalkElevation?.(ll.lng, ll.lat) ?? this.getElevation(ll.lng, ll.lat);
    const feetY = surface - this.originElev + this.verticalOffset;
    for (const tree of candidateTreeColliders(this, a, b, radius + .8)) {
      // The old engine disabled every tree collision above 2.4 m, allowing the
      // jetpack to pass through tall trunks. Only clear the collider above its
      // actual rendered top instead.
      if (Number.isFinite(tree.topY) && feetY > tree.topY + .25) continue;
      const rr = radius + tree.r;
      if (pointSegmentDistanceSq(a.x, a.z, b.x, b.z, tree.x, tree.z) <= rr * rr) return true;
    }
    return false;
  };
}

function stabilizeBuildingLayer(world, baseBuildingToggle) {
  // v0.17 hid the legacy instanced boxes, but GameWorld.render() set the group
  // visible=true again every frame. Those duplicate boxes were a major source of
  // apparent floating/sunken buildings. Keep the legacy group detached entirely.
  if (world.rectoradoDetail) {
    world.scene.add(world.rectoradoDetail);
    world.rectoradoDetail.visible = world.buildingsEnabled !== false;
  }
  disposeGroupChildren(world.buildingGroup);
  world.buildingGroup?.removeFromParent?.();
  if (world.materials) world.materials.building = null;
  world.__legacyBuildingGroupDetachedV0181 = true;

  world.setBuildingsEnabled = value => {
    const enabled = !!value;
    baseBuildingToggle?.(enabled);
    world.buildingsEnabled = enabled;
    if (world.buildingGroup) world.buildingGroup.visible = false;
    if (world.__campusArchitectureRootV017) world.__campusArchitectureRootV017.visible = enabled;
    if (world.__buildingFoundationRootV018) world.__buildingFoundationRootV018.visible = enabled;
    if (world.rectoradoDetail) world.rectoradoDetail.visible = enabled;
    world.forceRefresh = true;
  };
}

export function installRuntimeStabilityV0181(world, { baseBuildingToggle } = {}) {
  if (!world) return world;
  stabilizeBuildingLayer(world, baseBuildingToggle);
  installForestGuards(world);
  world.__runtimeStabilityV0181 = true;
  world.runtimeStabilityReport = Object.freeze({
    legacyBuildingLayerDetached: !!world.__legacyBuildingGroupDetachedV0181,
    forestHeightAwareCollision: !!world.__forestStabilityV0181,
    dynamicFoundationModel: !!world.__walkSurfaceRenderV018,
    rectoradoReparented: !!world.rectoradoDetail?.parent,
    hiddenBuildingFloorsDisabled: true
  });
  return world;
}
